### ISSUE TITLE
UnicodeDecodeError when converting sql to csv

### ISSUE THREAD

**Issue by MBmasher** [MBmasher/get-performance-data#1]
```
Traceback (most recent call last):
  File "get_performance_data.py", line 192, in <module>
    main()
  File "get_performance_data.py", line 188, in main
    sql_to_csv(directory_final + latest_file.split(".")[0] + "/")
  File "get_performance_data.py", line 93, in sql_to_csv
    sql_file_lines = [i.split("\n")[0] for i in sql_file_open.readlines()]
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2538: invalid start byte
```

This error occurs when converting specific files from sql to csv

The specific file I had this error in is `2019_04_01_performance_mania_random/osu_beatmapsets.sql`

**Comment by MBmasher** [comment]
Fixed in commit 96721bf264a73828034e69fae8d03241a102e234 yes good job me i am good at code
