### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGTSTP'

### ISSUE THREAD

**Issue by praeludiumOrbis** [MBmasher/get-performance-data#3]
```
E:\get-performance-data>get_performance_data.py
Traceback (most recent call last):
  File "E:\get-performance-data\get_performance_data.py", line 233, in <module>
    main()
  File "E:\get-performance-data\get_performance_data.py", line 203, in main
    signal.signal(signal.SIGTSTP, exit)
AttributeError: module 'signal' has no attribute 'SIGTSTP'
```
Am on Windows 10, Python 3.8.10.

**Comment by MBmasher** [comment]
Cant remember how this code worked since i wrote it ages ago but i think u need to run it on linux, or just remove the signal stuff altogether

**Comment by praeludiumOrbis** [comment]
Yep, I removed the Signal stuff, and it works now. Thanks for writing this!
